// SPDX-License-Identifier: MIT
import { Resend } from "resend";
// Initialiser Resend seulement si la clé API est fournie
import { env } from "./env";
import { logger } from "./logger";

const resend = env.RESEND_API_KEY ? new Resend(env.RESEND_API_KEY) : null;

/**
 * Send verification email to user
 * @param to - User email address
 * @param url - Verification URL generated by Better-Auth (contains token and callbackURL)
 * @param token - Verification token (provided for reference, already in URL)
 *
 * Note: Better-Auth generates the verification URL automatically.
 * The URL format is: /api/auth/verify-email?token=...&callbackURL=...
 * When user clicks the link, Better-Auth verifies the email and redirects to callbackURL.
 */
export async function sendVerificationEmail({
	to,
	url,
	token: _token,
}: {
	to: string;
	url: string; // URL générée par Better-Auth avec token et callbackURL
	token: string; // Fourni par Better-Auth mais déjà inclus dans l'URL
}) {
	// Vérifier que Resend est configuré
	if (!resend) {
		logger.error(
			"RESEND_API_KEY is not configured. Email verification cannot be sent.",
		);
		return;
	}

	// Ne pas await pour éviter les timing attacks
	// L'URL contient déjà le token et le callbackURL configuré par Better-Auth
	void resend.emails.send({
		from: env.EMAIL_FROM || "Calendraft <noreply@calendraft.com>",
		to,
		subject: "Verify your email address - Calendraft",
		html: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #18181b;">Verify your email address</h1>
          <p>Thank you for signing up for Calendraft! Please click the button below to verify your email address:</p>
          <div style="text-align: center; margin: 30px 0;">
            <a href="${url}" style="display: inline-block; background-color: #18181b; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 500;">Verify Email Address</a>
          </div>
          <p style="color: #666; font-size: 14px;">Or copy and paste this link into your browser:</p>
          <p style="color: #666; font-size: 14px; word-break: break-all;">${url}</p>
          <p style="color: #666; font-size: 14px; margin-top: 30px;">This link will expire in 1 hour.</p>
          <p style="color: #666; font-size: 14px;">If you didn't create an account, you can safely ignore this email.</p>
        </body>
      </html>
    `,
		text: `Verify your email address

Thank you for signing up for Calendraft! Please click the link below to verify your email address:

${url}

This link will expire in 1 hour.

If you didn't create an account, you can safely ignore this email.`,
	});
}

/**
 * Send password reset email to user
 * @param to - User email address
 * @param url - Reset password URL generated by Better-Auth (contains token and callbackURL)
 * @param token - Reset token (provided for reference, already in URL)
 *
 * Note: Better-Auth generates the reset URL automatically.
 * The URL format is: /api/auth/reset-password?token=...&callbackURL=...
 * When user clicks the link, they'll be redirected to the callbackURL with the token.
 */
export async function sendResetPasswordEmail({
	to,
	url,
	token: _token,
}: {
	to: string;
	url: string; // URL générée par Better-Auth avec token et callbackURL
	token: string; // Fourni par Better-Auth mais déjà inclus dans l'URL
}) {
	// Vérifier que Resend est configuré
	if (!resend) {
		logger.error(
			"RESEND_API_KEY is not configured. Password reset email cannot be sent.",
		);
		return;
	}

	// Ne pas await pour éviter les timing attacks
	// L'URL contient déjà le token et le callbackURL configuré par Better-Auth
	void resend.emails.send({
		from: env.EMAIL_FROM || "Calendraft <noreply@calendraft.com>",
		to,
		subject: "Reset your password - Calendraft",
		html: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #18181b;">Reset your password</h1>
          <p>We received a request to reset your password for your Calendraft account. Click the button below to reset it:</p>
          <div style="text-align: center; margin: 30px 0;">
            <a href="${url}" style="display: inline-block; background-color: #18181b; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 500;">Reset Password</a>
          </div>
          <p style="color: #666; font-size: 14px;">Or copy and paste this link into your browser:</p>
          <p style="color: #666; font-size: 14px; word-break: break-all;">${url}</p>
          <p style="color: #666; font-size: 14px; margin-top: 30px;">This link will expire in 1 hour.</p>
          <p style="color: #666; font-size: 14px;">If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.</p>
        </body>
      </html>
    `,
		text: `Reset your password

We received a request to reset your password for your Calendraft account. Click the link below to reset it:

${url}

This link will expire in 1 hour.

If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.`,
	});
}
