/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarsRouteImport } from './routes/calendars'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarsNewRouteImport } from './routes/calendars/new'
import { Route as CalendarsMergeRouteImport } from './routes/calendars/merge'
import { Route as CalendarsImportRouteImport } from './routes/calendars/import'
import { Route as CalendarsCalendarIdRouteImport } from './routes/calendars/$calendarId'
import { Route as CalendarsCalendarIdImportRouteImport } from './routes/calendars/$calendarId/import'
import { Route as CalendarsCalendarIdEventsNewRouteImport } from './routes/calendars/$calendarId/events/new'
import { Route as CalendarsCalendarIdEventsEventIdRouteImport } from './routes/calendars/$calendarId/events/$eventId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsRoute = CalendarsRouteImport.update({
  id: '/calendars',
  path: '/calendars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsNewRoute = CalendarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CalendarsRoute,
} as any)
const CalendarsMergeRoute = CalendarsMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => CalendarsRoute,
} as any)
const CalendarsImportRoute = CalendarsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => CalendarsRoute,
} as any)
const CalendarsCalendarIdRoute = CalendarsCalendarIdRouteImport.update({
  id: '/$calendarId',
  path: '/$calendarId',
  getParentRoute: () => CalendarsRoute,
} as any)
const CalendarsCalendarIdImportRoute =
  CalendarsCalendarIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => CalendarsCalendarIdRoute,
  } as any)
const CalendarsCalendarIdEventsNewRoute =
  CalendarsCalendarIdEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => CalendarsCalendarIdRoute,
  } as any)
const CalendarsCalendarIdEventsEventIdRoute =
  CalendarsCalendarIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => CalendarsCalendarIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendars': typeof CalendarsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRouteWithChildren
  '/calendars/import': typeof CalendarsImportRoute
  '/calendars/merge': typeof CalendarsMergeRoute
  '/calendars/new': typeof CalendarsNewRoute
  '/calendars/$calendarId/import': typeof CalendarsCalendarIdImportRoute
  '/calendars/$calendarId/events/$eventId': typeof CalendarsCalendarIdEventsEventIdRoute
  '/calendars/$calendarId/events/new': typeof CalendarsCalendarIdEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendars': typeof CalendarsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRouteWithChildren
  '/calendars/import': typeof CalendarsImportRoute
  '/calendars/merge': typeof CalendarsMergeRoute
  '/calendars/new': typeof CalendarsNewRoute
  '/calendars/$calendarId/import': typeof CalendarsCalendarIdImportRoute
  '/calendars/$calendarId/events/$eventId': typeof CalendarsCalendarIdEventsEventIdRoute
  '/calendars/$calendarId/events/new': typeof CalendarsCalendarIdEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendars': typeof CalendarsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRouteWithChildren
  '/calendars/import': typeof CalendarsImportRoute
  '/calendars/merge': typeof CalendarsMergeRoute
  '/calendars/new': typeof CalendarsNewRoute
  '/calendars/$calendarId/import': typeof CalendarsCalendarIdImportRoute
  '/calendars/$calendarId/events/$eventId': typeof CalendarsCalendarIdEventsEventIdRoute
  '/calendars/$calendarId/events/new': typeof CalendarsCalendarIdEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendars'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/calendars/$calendarId'
    | '/calendars/import'
    | '/calendars/merge'
    | '/calendars/new'
    | '/calendars/$calendarId/import'
    | '/calendars/$calendarId/events/$eventId'
    | '/calendars/$calendarId/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendars'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/calendars/$calendarId'
    | '/calendars/import'
    | '/calendars/merge'
    | '/calendars/new'
    | '/calendars/$calendarId/import'
    | '/calendars/$calendarId/events/$eventId'
    | '/calendars/$calendarId/events/new'
  id:
    | '__root__'
    | '/'
    | '/calendars'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/calendars/$calendarId'
    | '/calendars/import'
    | '/calendars/merge'
    | '/calendars/new'
    | '/calendars/$calendarId/import'
    | '/calendars/$calendarId/events/$eventId'
    | '/calendars/$calendarId/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarsRoute: typeof CalendarsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars': {
      id: '/calendars'
      path: '/calendars'
      fullPath: '/calendars'
      preLoaderRoute: typeof CalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/new': {
      id: '/calendars/new'
      path: '/new'
      fullPath: '/calendars/new'
      preLoaderRoute: typeof CalendarsNewRouteImport
      parentRoute: typeof CalendarsRoute
    }
    '/calendars/merge': {
      id: '/calendars/merge'
      path: '/merge'
      fullPath: '/calendars/merge'
      preLoaderRoute: typeof CalendarsMergeRouteImport
      parentRoute: typeof CalendarsRoute
    }
    '/calendars/import': {
      id: '/calendars/import'
      path: '/import'
      fullPath: '/calendars/import'
      preLoaderRoute: typeof CalendarsImportRouteImport
      parentRoute: typeof CalendarsRoute
    }
    '/calendars/$calendarId': {
      id: '/calendars/$calendarId'
      path: '/$calendarId'
      fullPath: '/calendars/$calendarId'
      preLoaderRoute: typeof CalendarsCalendarIdRouteImport
      parentRoute: typeof CalendarsRoute
    }
    '/calendars/$calendarId/import': {
      id: '/calendars/$calendarId/import'
      path: '/import'
      fullPath: '/calendars/$calendarId/import'
      preLoaderRoute: typeof CalendarsCalendarIdImportRouteImport
      parentRoute: typeof CalendarsCalendarIdRoute
    }
    '/calendars/$calendarId/events/new': {
      id: '/calendars/$calendarId/events/new'
      path: '/events/new'
      fullPath: '/calendars/$calendarId/events/new'
      preLoaderRoute: typeof CalendarsCalendarIdEventsNewRouteImport
      parentRoute: typeof CalendarsCalendarIdRoute
    }
    '/calendars/$calendarId/events/$eventId': {
      id: '/calendars/$calendarId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/calendars/$calendarId/events/$eventId'
      preLoaderRoute: typeof CalendarsCalendarIdEventsEventIdRouteImport
      parentRoute: typeof CalendarsCalendarIdRoute
    }
  }
}

interface CalendarsCalendarIdRouteChildren {
  CalendarsCalendarIdImportRoute: typeof CalendarsCalendarIdImportRoute
  CalendarsCalendarIdEventsEventIdRoute: typeof CalendarsCalendarIdEventsEventIdRoute
  CalendarsCalendarIdEventsNewRoute: typeof CalendarsCalendarIdEventsNewRoute
}

const CalendarsCalendarIdRouteChildren: CalendarsCalendarIdRouteChildren = {
  CalendarsCalendarIdImportRoute: CalendarsCalendarIdImportRoute,
  CalendarsCalendarIdEventsEventIdRoute: CalendarsCalendarIdEventsEventIdRoute,
  CalendarsCalendarIdEventsNewRoute: CalendarsCalendarIdEventsNewRoute,
}

const CalendarsCalendarIdRouteWithChildren =
  CalendarsCalendarIdRoute._addFileChildren(CalendarsCalendarIdRouteChildren)

interface CalendarsRouteChildren {
  CalendarsCalendarIdRoute: typeof CalendarsCalendarIdRouteWithChildren
  CalendarsImportRoute: typeof CalendarsImportRoute
  CalendarsMergeRoute: typeof CalendarsMergeRoute
  CalendarsNewRoute: typeof CalendarsNewRoute
}

const CalendarsRouteChildren: CalendarsRouteChildren = {
  CalendarsCalendarIdRoute: CalendarsCalendarIdRouteWithChildren,
  CalendarsImportRoute: CalendarsImportRoute,
  CalendarsMergeRoute: CalendarsMergeRoute,
  CalendarsNewRoute: CalendarsNewRoute,
}

const CalendarsRouteWithChildren = CalendarsRoute._addFileChildren(
  CalendarsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarsRoute: CalendarsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
