#!/bin/bash
# Aide pour les scripts de production
# Usage: ./help.sh [script]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

show_help() {
    local script="$1"
    
    case "$script" in
        deploy)
            echo "🚀 Script de Déploiement"
            echo "========================="
            echo ""
            echo "Usage: ./deploy.sh [options]"
            echo ""
            echo "Options:"
            echo "  --backup          Créer une sauvegarde avant le déploiement"
            echo "  --migrate         Appliquer les migrations de base de données"
            echo "  --service=SERVICE Déployer uniquement un service (web, server, etc.)"
            echo ""
            echo "Exemples:"
            echo "  ./deploy.sh"
            echo "  ./deploy.sh --backup"
            echo "  ./deploy.sh --backup --migrate"
            echo "  ./deploy.sh --service=web"
            ;;
        backup)
            echo "💾 Script de Sauvegarde"
            echo "======================="
            echo ""
            echo "Usage: ./backup.sh [options]"
            echo ""
            echo "Options:"
            echo "  --list                    Lister les sauvegardes disponibles"
            echo "  --restore=FICHIER         Restaurer une sauvegarde"
            echo ""
            echo "Exemples:"
            echo "  ./backup.sh"
            echo "  ./backup.sh --list"
            echo "  ./backup.sh --restore=~/backups/db-backup-20251213-120000.sql.gz"
            ;;
        monitor)
            echo "📊 Script de Monitoring"
            echo "======================"
            echo ""
            echo "Usage: ./monitor.sh [options]"
            echo ""
            echo "Options:"
            echo "  --all      Afficher toutes les informations"
            echo "  --health   Afficher l'état de santé"
            echo "  --stats    Afficher les statistiques de ressources"
            echo "  --logs     Afficher les logs récents"
            echo "  --errors   Afficher les erreurs récentes"
            echo ""
            echo "Exemples:"
            echo "  ./monitor.sh --all"
            echo "  ./monitor.sh --health"
            echo "  ./monitor.sh --stats"
            ;;
        health-check)
            echo "🏥 Script de Vérification de Santé"
            echo "==================================="
            echo ""
            echo "Usage: ./health-check.sh [options]"
            echo ""
            echo "Options:"
            echo "  --verbose  Afficher les détails des vérifications"
            echo ""
            echo "Exemples:"
            echo "  ./health-check.sh"
            echo "  ./health-check.sh --verbose"
            ;;
        cleanup)
            echo "🧹 Script de Nettoyage"
            echo "======================"
            echo ""
            echo "Usage: ./cleanup.sh [options]"
            echo ""
            echo "Options:"
            echo "  --all          Nettoyer images, cache et logs"
            echo "  --images       Nettoyer les images inutilisées"
            echo "  --volumes      Nettoyer les volumes inutilisés (⚠️  destructif)"
            echo "  --logs         Nettoyer les logs"
            echo "  --system       Nettoyage complet du système (⚠️  très destructif)"
            echo "  --build-cache  Nettoyer le cache de build"
            echo ""
            echo "Exemples:"
            echo "  ./cleanup.sh --all"
            echo "  ./cleanup.sh --images"
            echo "  ./cleanup.sh --build-cache"
            ;;
        quick-commands)
            echo "⚡ Commandes Rapides"
            echo "===================="
            echo ""
            echo "Usage: ./quick-commands.sh [command] [service]"
            echo ""
            echo "Commandes:"
            echo "  status, ps          Statut des services"
            echo "  logs [service]      Logs en temps réel"
            echo "  restart [service]   Redémarrer"
            echo "  stop [service]      Arrêter"
            echo "  start [service]     Démarrer"
            echo "  shell-db            Shell PostgreSQL"
            echo "  shell-server        Shell backend"
            echo "  shell-web           Shell frontend"
            echo "  stats               Statistiques"
            echo "  top                 Processus"
            echo "  env                 Configuration"
            echo ""
            echo "Exemples:"
            echo "  ./quick-commands.sh status"
            echo "  ./quick-commands.sh logs server"
            echo "  ./quick-commands.sh restart web"
            ;;
        rollback)
            echo "🔄 Script de Rollback"
            echo "====================="
            echo ""
            echo "Usage: ./rollback.sh [options]"
            echo ""
            echo "Options:"
            echo "  --commit=HASH       Commit spécifique (sinon demande)"
            echo "  --no-backup         Ne pas créer de sauvegarde avant rollback"
            echo "  --no-db             Ne pas restaurer la base de données"
            echo ""
            echo "Exemples:"
            echo "  ./rollback.sh"
            echo "  ./rollback.sh --commit=abc123"
            echo "  ./rollback.sh --commit=HEAD~1 --no-backup"
            ;;
        verify-backup)
            echo "🔍 Vérification de Sauvegarde"
            echo "============================="
            echo ""
            echo "Usage: ./verify-backup.sh [FILE]"
            echo ""
            echo "Si FILE est fourni, vérifie ce fichier spécifique."
            echo "Sinon, vérifie toutes les sauvegardes dans BACKUP_DIR."
            echo ""
            echo "Exemples:"
            echo "  ./verify-backup.sh"
            echo "  ./verify-backup.sh ~/backups/db-backup-20251213.sql.gz"
            ;;
        security-audit)
            echo "🔒 Audit de Sécurité"
            echo "==================="
            echo ""
            echo "Usage: ./security-audit.sh [options]"
            echo ""
            echo "Options:"
            echo "  --verbose           Afficher les détails des vérifications"
            echo ""
            echo "Vérifie:"
            echo "  - Certificats SSL"
            echo "  - Headers de sécurité"
            echo "  - Variables d'environnement"
            echo "  - Configuration Docker"
            echo "  - Exposition des ports"
            echo ""
            echo "Exemples:"
            echo "  ./security-audit.sh"
            echo "  ./security-audit.sh --verbose"
            ;;
        report)
            echo "📊 Rapport d'État"
            echo "================"
            echo ""
            echo "Usage: ./report.sh [options]"
            echo ""
            echo "Options:"
            echo "  --format=text|json  Format du rapport (défaut: text)"
            echo "  --output=FILE        Fichier de sortie (défaut: stdout)"
            echo ""
            echo "Exemples:"
            echo "  ./report.sh"
            echo "  ./report.sh --format=json --output=report.json"
            echo "  ./report.sh --format=text --output=report.txt"
            ;;
        install)
            echo "📦 Script d'Installation"
            echo "========================"
            echo ""
            echo "Usage: ./install.sh user@server"
            echo ""
            echo "Installe tous les scripts de production sur un serveur distant."
            echo ""
            echo "Exemples:"
            echo "  ./install.sh root@185.158.132.190"
            echo "  ./install.sh user@example.com"
            echo ""
            echo "Le script copie:"
            echo "  - Tous les scripts .sh dans ~/calendraft/scripts/production/"
            echo "  - PRODUCTION_COMMANDS.md dans ~/calendraft/"
            ;;
        *)
            echo "📚 Aide - Scripts de Production Calendraft"
            echo "=========================================="
            echo ""
            echo "Scripts disponibles:"
            echo ""
            echo "  🚀 deploy.sh          - Déploiement de l'application"
            echo "  💾 backup.sh          - Sauvegarde et restauration"
            echo "  🔄 rollback.sh         - Retour à une version précédente"
            echo "  📊 monitor.sh         - Monitoring et statistiques"
            echo "  🏥 health-check.sh     - Vérification de santé"
            echo "  🔒 security-audit.sh   - Audit de sécurité"
            echo "  🔍 verify-backup.sh    - Vérification d'intégrité des sauvegardes"
            echo "  📊 report.sh           - Rapport d'état (texte/JSON)"
            echo "  🧹 cleanup.sh         - Nettoyage Docker"
            echo "  ⚡ quick-commands.sh   - Commandes rapides"
            echo "  📦 install.sh         - Installation sur serveur distant"
            echo "  ❓ help.sh            - Aide intégrée (ce script)"
            echo ""
            echo "Usage:"
            echo "  ./help.sh [script]    - Aide pour un script spécifique"
            echo ""
            echo "Exemples:"
            echo "  ./help.sh deploy"
            echo "  ./help.sh backup"
            echo "  ./help.sh rollback"
            echo ""
            echo "Pour plus d'informations, consultez:"
            echo "  ~/calendraft/PRODUCTION_COMMANDS.md"
            echo "  scripts/production/README.md"
            ;;
    esac
}

show_help "${1:-}"

